Repository CleverCloud/documentation, pull requests merged in 2024-04, with the labels that each got.

#233 Update CI/CD documentation
  .github/styles/config/vocabularies/Doc/accept.txt
  content/doc/addons/heptapod.md
  content/doc/ci-cd/_index.md
  content/doc/ci-cd/custom-scripts.md
  content/doc/ci-cd/github.md
  content/doc/ci-cd/gitlab.md
  layouts/shortcodes/content/ci-cd-configuration.md
Labels: documentation

#237 changelog: CVE-2024-3094
  content/changelog/2024-04-04-CVE-2024-3094.md
Labels: changelog

#230 Revamp for content/doc/applications/dotnet/_index.md: replace lists by cards and update links
  content/doc/applications/dotnet/_index.md
  content/doc/develop/env-variables.md
  content/guides/play-framework-1.md
  content/guides/play-framework-2.md
  layouts/partials/add-ssh-keys-short-version/index.html
  layouts/partials/authentication/index.html
  layouts/partials/bintray-to-nexus/index.html
  layouts/partials/blackfire/index.html
  layouts/partials/cached-dependencies/index.html
  layouts/partials/create-application/index.html
  layouts/partials/db-backup/index.html
  layouts/partials/deploy-ftp/index.html
  layouts/partials/deploy-git/index.html
  layouts/partials/env-injection/index.html
  layouts/partials/index.html
  layouts/partials/java-versions/index.html
  layouts/partials/language-specific-deploy/docker/index.html
  layouts/partials/language-specific-deploy/dotnet/index.html
  layouts/partials/language-specific-deploy/elixir/index.html
  layouts/partials/language-specific-deploy/go/index.html
  layouts/partials/language-specific-deploy/haskell/index.html
  layouts/partials/language-specific-deploy/java/index.html
  layouts/partials/language-specific-deploy/node/index.html
  layouts/partials/language-specific-deploy/php/index.html
  layouts/partials/language-specific-deploy/python/index.html
  layouts/partials/language-specific-deploy/ruby/index.html
  layouts/partials/language-specific-deploy/rust/index.html
  layouts/partials/language-specific-deploy/scala/index.html
  layouts/partials/link-addon/index.html
  layouts/partials/more-config/index.html
  layouts/partials/new-relic/index.html
  layouts/partials/pgpool/index.html
  layouts/partials/proxysql/index.html
  layouts/partials/set-env-vars/index.html
  layouts/partials/single-sign-on/index.html
  layouts/partials/ssh-keys/index.html
Labels: documentation

#238 fix: drop deprecated providers logs
  content/doc/extend/_index.md
  content/doc/extend/add-ons-api.md
  content/doc/extend/add-ons-log-collector.md
  layouts/partials/add-ssh-keys-short-version/index.html
  layouts/partials/authentication/index.html
  layouts/partials/bintray-to-nexus/index.html
  layouts/partials/blackfire/index.html
  layouts/partials/cached-dependencies/index.html
  layouts/partials/create-application/index.html
  layouts/partials/db-backup/index.html
  layouts/partials/deploy-ftp/index.html
  layouts/partials/deploy-git/index.html
  layouts/partials/env-injection/index.html
  layouts/partials/index.html
  layouts/partials/java-versions/index.html
  layouts/partials/language-specific-deploy/docker/index.html
  layouts/partials/language-specific-deploy/dotnet/index.html
  layouts/partials/language-specific-deploy/elixir/index.html
  layouts/partials/language-specific-deploy/go/index.html
  layouts/partials/language-specific-deploy/haskell/index.html
  layouts/partials/language-specific-deploy/java/index.html
  layouts/partials/language-specific-deploy/node/index.html
  layouts/partials/language-specific-deploy/php/index.html
  layouts/partials/language-specific-deploy/python/index.html
  layouts/partials/language-specific-deploy/ruby/index.html
  layouts/partials/language-specific-deploy/rust/index.html
  layouts/partials/language-specific-deploy/scala/index.html
  layouts/partials/link-addon/index.html
  layouts/partials/more-config/index.html
  layouts/partials/new-relic/index.html
  layouts/partials/pgpool/index.html
  layouts/partials/proxysql/index.html
  layouts/partials/set-env-vars/index.html
  layouts/partials/single-sign-on/index.html
  layouts/partials/ssh-keys/index.html
Labels: documentation, waiting

#241 fix(docs/domain-names): remove auto monitoring mention
  content/doc/administrate/domain-names.md
Labels: documentation

#236 Update Cellar doc
  .github/styles/config/vocabularies/Doc/accept.txt
  archetypes/default.md
  content/doc/addons/cellar.md
Labels: documentation

#243 Fix wordpress documentation regarding mysql non-default port.
  content/guides/tutorial-wordpress.md
Labels: documentation, waiting

#248 Initial doc for MateriaDB KV
  content/doc/addons/materia-db-kv.md
Labels: documentation, waiting

#242 Fix invoice payment schedule documentation.
  content/doc/billing/payments-invoicing.md
  content/doc/billing/unified-invoices.md
Labels: documentation

#253 changelog: Clever Tools 3.5.2
  content/changelog/2024-04-11-clever-tools-3.5.2.md
Labels: changelog

#251 MateriaDB KV - Add last missing commands
  content/doc/addons/materia-db-kv.md
Labels: documentation

#244 CI/CD: add PROJECT_PATH configuration details to prevent errors from users
  content/doc/ci-cd/gitlab.md
Labels: documentation
