Repository CleverCloud/documentation, pull requests merged in 2024-01, with the labels that each got.

#123 update CC_RUN_COMMAND + fix default callout in dark mode
  assets/css/custom.css
  content/doc/reference/reference-environment-variables.md
  layouts/shortcodes/callout.html
Labels: documentation, enhancement

#115 Add description to Account section pages
  content/doc/account/_index.md
  content/doc/account/administrate-organization.md
  content/doc/account/create-account.md
  content/doc/account/delete-account.md
  content/doc/account/manage-account.md
  content/doc/account/notifications.md
  content/doc/account/organizations.md
  content/doc/account/ssh-keys-management.md
Labels: waiting

#122 guides: Add instructions for multiple SSG tools
  content/guides/_index.md
  content/guides/astro.md
  content/guides/docusaurus.md
  content/guides/eleventy.md
  content/guides/hexo.md
  content/guides/hugo.md
  content/guides/lume-deno.md
  content/guides/mdbook.md
  content/guides/mkdocs.md
  content/guides/nuxt.md
  data/icons.yaml
  static/partials/guides/create-static.md
  static/partials/guides/git-push.md
Labels: documentation

#136 Create Moodle guide
  content/guides/_index.md
  content/guides/kibana.md
  content/guides/moodle.md
  data/icons.yaml
  hugo.yaml
  static/images/feature.png
Labels: documentation

#130 Add references to CC_DISABLE_BUILD_CACHE_UPLOAD
  content/doc/administrate/apps-management.md
  content/doc/develop/build-hooks.md
  content/doc/develop/env-variables.md
  content/doc/reference/reference-environment-variables.md
Labels: documentation, waiting

#137 docs: Adding a new Heptapod page
  content/doc/addons/heptapod.md
  static/images/doc/app-management.png
  static/images/doc/clever-cloud-runners-basic-with-runtimes-alt.svg
  static/images/doc/heptapod-billing.png
Labels: documentation, waiting

#141 fix: Prometheus port in env vars reference
  content/doc/reference/reference-environment-variables.md
Labels: documentation

#153 New content issue template
  .github/ISSUE_TEMPLATE/new-content-form.yaml
Labels: bug

#144 feat(elasticsearch): add create index doc
  content/doc/addons/elastic/_index.md
Labels: documentation

#165 structure API documentation
  content/_index.md
  content/api/_index.md
  content/api/howto.md
  content/api/v2.md
  content/api/v4.md
  content/doc/extend/_index.md
  content/doc/quickstart/_index.md
  content/openapi.md
  data/icons.yaml
  hugo.yaml
Labels: documentation

#173 fix: typography in Matomo page
  content/doc/addons/matomo.md
Labels: documentation

#169 fix: set featured image to 1600 x 900 px
  static/images/feature.png
Labels: bug
