Repository CleverCloud/documentation, pull requests merged in 2024-09, with the labels that each got.

#366 Hugo version setup
  .github/workflows/review-app.yml
  go.mod
  hugo.yaml
Labels: enhancement

#372 chore: upgrade from version 0.133.1 to version 0.134.1
  .github/workflows/review-app.yml
  hugo.yaml
Labels: enhancement

#370 Changelog: back to school 2024 update
  content/changelog/2024-07-12-accountant-access-console-fix.md
  content/changelog/2024-07-17-keycloak-public-release.md
  content/changelog/2024-07-17-new-logs-default.md
  content/changelog/2024-07-18-elastic-8.10.2-jenkins-2.452.3.md
  content/changelog/2024-07-18-github-action-review-apps.md
  content/changelog/2024-07-26-domains-console-update.md
  content/changelog/2024-07-30-github-action-1.1.md
  content/changelog/2024-08-01-lagging-server-crate.md
  content/changelog/2024-08-09-python-3.12-update.md
  content/changelog/2024-08-26-java-containers-update.md
  content/changelog/2024-08-30-deploy-url-mtl.md
  content/changelog/2024-09-03-gitlab-components-review-apps.md
  content/doc/administrate/domain-names.md
Labels: documentation, waiting, changelog

#373 Minor improvements
  .gitignore
  .hugo_build.lock
  README.md
  data/icons.yaml
Labels: documentation

#374 fix: YouTube privacy parameter ident
  hugo.yaml
Labels: bug

#375 changelog: fix typo and add breaking changes warning
  content/changelog/2024-09-03-gitlab-components-review-apps.md
Labels: changelog

#379 doc: specify Docker image steps
  content/doc/applications/docker/_index.md
Labels: documentation, waiting
