Repository CleverCloud/documentation, pull requests merged in 2024-03, with the labels that each got.

#213 chore: fix add-on api page rendering
  assets/css/custom.css
  content/doc/extend/add-ons-api.md
Labels: bug

#216 Create guide archetype
  .github/styles/Guides/ellipsis.yml
  .github/styles/config/vocabularies/Doc/accept.txt
  .vale.ini
  README.md
  archetypes/guides.md
  data/icons.yaml
Labels: enhancement

#219 fix(apiv2-page): prevent conflicts with the global "/" shortcut
  layouts/openapi/single.html
Labels: bug

#210 changelog: images update part2
  content/changelog/2024-02-27-images-update-part2.md
  content/doc/applications/dotnet/_index.md
  content/doc/reference/reference-environment-variables.md
Labels: waiting, changelog
