Repository CleverCloud/documentation, pull requests merged in 2024-08, with the labels that each got.

#356 fix: vale and adding info about organizations
  content/doc/account/administrate-organization.md
  content/doc/account/manage-account.md
Labels: documentation

#354 changelog: Python image update
  content/changelog/2024-08-09-python-3.12-update.md
Labels: changelog

#324 Runtime software versioning data
  .github/workflows/review-app.yml
  content/doc/addons/elastic/_index.md
  content/doc/addons/mongodb/_index.md
  content/doc/addons/mysql/_index.md
  content/doc/addons/postgresql/_index.md
  content/doc/addons/redis.md
  content/doc/applications/dotnet/_index.md
  content/doc/applications/elixir/_index.md
  content/doc/applications/java/java-gradle.md
  content/doc/applications/java/java-jar.md
  content/doc/applications/java/java-maven.md
  content/doc/applications/java/java-war.md
  content/doc/applications/javascript/nodejs.md
  content/doc/applications/php/_index.md
  content/doc/applications/python/_index.md
  data/runtime_versions.yml
  data/software_versions_shared_dedicated.yml
  layouts/shortcodes/content/java-versions.md
  layouts/shortcodes/runtimes_versions.html
  layouts/shortcodes/software_versions_shared_dedicated.html
Labels: enhancement

#353 Use Varnish in a monorepo
  content/doc/administrate/cache.md
Labels: documentation, discuss

#357 update_accesslogs_option
  content/doc/administrate/log-management.md
Labels: documentation, waiting

#365 doc: document drain log to Logs Data Platform on OVH
  content/doc/administrate/log-management.md
Labels: documentation
