Repository CleverCloud/documentation, pull requests merged in 2024-06, with the labels that each got.

#285 style: create Materia card
  content/doc/addons/_index.md
  data/icons.yaml
Labels: documentation

#281 doc: add limited rights disclaimer on db pages
  content/doc/addons/elastic/_index.md
  content/doc/addons/materia-kv.md
  content/doc/addons/mongodb/_index.md
  content/doc/addons/mysql/_index.md
  content/doc/addons/postgresql/_index.md
  content/doc/addons/redis.md
  layouts/shortcodes/content/managed-services.md
Labels: documentation

#294 Document usage of CC_HEALTH_CHECK_PATH in blue-green deployment.
  content/doc/best-practices/blue-green.md
  layouts/shortcodes/content/url_healthcheck.md
Labels: documentation, waiting

#303 docs(marketplace): init section from Add-on provider API page
  content/doc/_index.md
  content/doc/extend/_index.md
  content/doc/marketplace/_index.md
Labels: documentation, waiting

#299 Hextra v0.7.3 => v0.8.0
  assets/css/custom.css
  content/_index.md
  content/doc/addons/keycloak.md
  content/doc/quickstart/_index.md
  go.mod
  go.sum
  layouts/404.html
  layouts/changelog/list.html
  layouts/changelog/single.html
  layouts/docs/single.html
  layouts/partials/components/feedback.html
  layouts/partials/index.html
  layouts/shortcodes/callout.html
  layouts/shortcodes/card.html
  layouts/shortcodes/cards.html
  layouts/shortcodes/code.html
  layouts/shortcodes/details.html
  layouts/shortcodes/feature-card.html
  layouts/shortcodes/feature-grid.html
  layouts/shortcodes/hero-button-primary.html
  layouts/shortcodes/hero-button-secondary.html
  layouts/shortcodes/icon.html
  layouts/shortcodes/img-grid.html
  layouts/shortcodes/imgproc.html
  layouts/shortcodes/steps.html
  layouts/shortcodes/tab.html
  layouts/shortcodes/tabs.html
Labels: enhancement

#306 Fix: tables in dark mode
  assets/css/custom.css
  layouts/shortcodes/feature-card.html
Labels: enhancement
