Repository CleverCloud/documentation, pull requests merged in 2024-07, with the labels that each got.

#320 Add custom certificates correction
  content/doc/administrate/ssl.md
Labels: documentation

#329 doc: add demo video to quickstart page
  content/doc/quickstart/_index.md
Labels: documentation

#309 Add Ports explanation to troubleshootingp page
  content/doc/find-help/troubleshooting.md
Labels: documentation, waiting

#339 doc: update GitHub Action instructions
  content/doc/ci-cd/github.md
Labels: documentation

#325 Database backup explanation
  content/doc/find-help/faq.md
Labels: documentation

#344 styles: update card partial to fit current Hextra configuration
  layouts/partials/shortcodes/card.html
  layouts/shortcodes/card.html
Labels: enhancement

#343 Add warning on installing clever tools with apple processor
  content/doc/CLI/getting_started.md
Labels: documentation, waiting

#347 doc: add activity page with explanations on monitoring re-deployments
  content/doc/administrate/activity.md
  static/images/doc/activity.png
  static/images/doc/monitoring.png
Labels: documentation
