Repository CleverCloud/documentation, pull requests merged in 2024-02, with the labels that each got.

#182 changelog: add February images update part 1
  content/changelog/2024-02-02-images-update.md
Labels: waiting, changelog

#134 fix: Go build/deploy page revamp
  content/doc/applications/golang/_index.md
  content/doc/reference/reference-environment-variables.md
  static/partials/language-specific-deploy/go.md
Labels: waiting

#184 Automate editorial style checking
  .github/styles/.vale-config/1-Hugo.ini
  .github/styles/Google/AMPM.yml
  .github/styles/Google/Acronyms.yml
  .github/styles/Google/Colons.yml
  .github/styles/Google/Contractions.yml
  .github/styles/Google/DateFormat.yml
  .github/styles/Google/Ellipses.yml
  .github/styles/Google/EmDash.yml
  .github/styles/Google/EnDash.yml
  .github/styles/Google/Exclamation.yml
  .github/styles/Google/FirstPerson.yml
  .github/styles/Google/Gender.yml
  .github/styles/Google/GenderBias.yml
  .github/styles/Google/HeadingPunctuation.yml
  .github/styles/Google/Headings.yml
  .github/styles/Google/Latin.yml
  .github/styles/Google/LyHyphens.yml
  .github/styles/Google/OptionalPlurals.yml
  .github/styles/Google/Ordinal.yml
  .github/styles/Google/OxfordComma.yml
  .github/styles/Google/Parens.yml
  .github/styles/Google/Passive.yml
  .github/styles/Google/Periods.yml
  .github/styles/Google/Quotes.yml
  .github/styles/Google/Ranges.yml
  .github/styles/Google/Semicolons.yml
  .github/styles/Google/Slang.yml
  .github/styles/Google/Spacing.yml
  .github/styles/Google/Spelling.yml
  .github/styles/Google/Units.yml
  .github/styles/Google/We.yml
  .github/styles/Google/Will.yml
  .github/styles/Google/WordList.yml
  .github/styles/Google/meta.json
  .github/styles/Google/vocab.txt
  .github/styles/config/vocabularies/Doc/accept.txt
  .github/styles/config/vocabularies/Doc/reject.txt
  .github/workflows/styles-review.yml
  .github/workflows/test-cli.yml.nope
  .gitignore
  .vale.ini
  content/doc/quickstart/_index.md
  content/guides/moodle.md
Labels: enhancement

#170 fix(add-ons-api): options is now supported
  content/doc/extend/add-ons-api.md
Labels: documentation

#201 indicate correct format of private key in TLS certificates to add
  content/doc/administrate/ssl.md
Labels: bug

#204 add moderation section in troubleshooting page
  content/doc/find-help/troubleshooting.md
Labels: documentation, waiting

#199 correct docker command
  content/doc/CLI/getting_started.md
Labels: documentation

#209 Document deployment healthcheck for all images.
  content/doc/applications/docker/_index.md
  content/doc/applications/dotnet/_index.md
  content/doc/applications/golang/_index.md
  content/doc/applications/javascript/meteor.md
  content/doc/applications/javascript/nodejs.md
  content/doc/applications/php/_index.md
  content/doc/applications/python/_index.md
  content/doc/applications/ruby/_index.md
  content/doc/applications/rust/_index.md
  content/doc/applications/scala/_index.md
Labels: changelog
