Repository CleverCloud/documentation, pull requests merged in 2024-10, with the labels that each got.

#392 Upgrade Hugo+Hextra version
  .github/workflows/review-app.yml
  .gitignore
  go.mod
  go.sum
  hugo.yaml
Labels: enhancement

#391 fix(domains names):readability and textual updates
  content/doc/administrate/domain-names.md
Labels: documentation

#384 Added QueuedTracking plugin info on matomo add-on page
  content/doc/addons/matomo.md
Labels: documentation, waiting

#382 add precision - leading to downtime of varying duration and scope
  content/postmortem/2024-08-02.md
Labels: waiting

#387 Fixing Jetty URLs and adding EOL status
  content/doc/applications/java/java-war.md
Labels: documentation
